import os
import re

template_dir = r"d:\dbmss\templates"

mega_dropdown = """<div class="relative group">
                    <button class="text-brand-lightgold hover:text-brand-gold font-medium transition-colors flex items-center">
                        Modules <svg class="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
                    </button>
                    <!-- Mega Dropdown for 10 Modules -->
                    <div class="absolute left-0 mt-2 w-56 bg-brand-dark border border-brand-gold/30 rounded-sm shadow-xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-300 z-50 grid grid-cols-1 divide-y divide-brand-gold/10">
                        <div class="py-1">
                            <p class="px-4 py-1 text-[10px] font-bold text-brand-gold uppercase tracking-wider">Core Supply</p>
                            <a href="{{ url_for('weaver_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">1. Weaver Mgmt</a>
                            <a href="{{ url_for('raw_material_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">2. Raw Materials</a>
                            <a href="{{ url_for('supplier_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">3. Suppliers</a>
                        </div>
                        <div class="py-1">
                            <p class="px-4 py-1 text-[10px] font-bold text-brand-gold uppercase tracking-wider">Production & Catalog</p>
                            <a href="{{ url_for('production_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">4. Production Tracking</a>
                            <a href="{{ url_for('product_catalog_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">5. Product Catalog</a>
                        </div>
                        <div class="py-1">
                            <p class="px-4 py-1 text-[10px] font-bold text-brand-gold uppercase tracking-wider">Enterprise ERP</p>
                            <a href="{{ url_for('order_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">6. Order Mgmt</a>
                            <a href="{{ url_for('customer_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">7. Customer Mgmt</a>
                            <a href="{{ url_for('inventory_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">8. Warehouse Inventory</a>
                            <a href="{{ url_for('billing_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">9. Payment & Billing</a>
                            <a href="{{ url_for('logistics_module') }}" class="block px-4 py-1.5 text-xs text-brand-lightgold hover:bg-brand-gold hover:text-brand-black transition-colors">10. Logistics Transport</a>
                        </div>
                    </div>
                </div>"""

# Re-run for files that were NOT generated by the generate_all_modules script
files_to_patch = ['dashboard.html', 'artisans.html', 'designs.html', 'materials.html', 'production_module.html']

for f in files_to_patch:
    filepath = os.path.join(template_dir, f)
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as file:
            content = file.read()
            
        # Match <div class="relative group"> up to the matching closing </div> for the dropdown block
        # Since regex is hard with nested divs, we'll match up to {% endif %} 
        # which comes right after the dropdown!
        pattern = r'<div class="relative group">.*?</div>\s*(?={%\s*endif\s*%})'
        # Wait, if there are multiple relative groups, this could break.
        # Let's match from <div class="relative group"> where it contains "Modules <svg"
        pattern2 = r'<div class="relative group">\s*<button[^>]*>\s*Modules <svg.*?</div>\s*</div>\s*(?={%\s*endif\s*%})'
        
        # A more robust approach for files mangled with newlines:
        import re
        
        # We can find the start index of "<div class="relative group">" immediately following "{% if session.get('role') == 'Admin' %}"
        admin_idx = content.find("{% if session.get('role') == 'Admin' %}")
        if admin_idx != -1:
            endif_idx = content.find("{% endif %}", admin_idx)
            if endif_idx != -1:
                # Replace everything between the Admin if and endif with the new dropdown
                new_content = content[:admin_idx + len("{% if session.get('role') == 'Admin' %}")] + "\n" + mega_dropdown + "\n                " + content[endif_idx:]
                with open(filepath, 'w', encoding='utf-8') as file:
                    file.write(new_content)
                print(f"Patched navigation in {f}")
